#!/bin/bash
set -e

HOOKS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.claude/claude-office-config.env"

echo "Installing hooks from: $HOOKS_DIR"

# Check for uv
if ! command -v uv &> /dev/null; then
    echo "Error: 'uv' is not installed. Please install it first."
    exit 1
fi

# Default strip prefixes - strips common path prefixes from project names
DEFAULT_PREFIXES="-Users-$USER-Repos-,-Users-$USER-"

# Parse arguments
STRIP_PREFIXES=""
FORCE=0
while [[ $# -gt 0 ]]; do
    case $1 in
        --strip-prefixes)
            STRIP_PREFIXES="$2"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--strip-prefixes 'prefix1,prefix2'] [--force]"
            echo "  --strip-prefixes  Comma-separated path prefixes to strip from project names"
            echo "  --force           Reset managed keys (prefixes/debug) to defaults, discarding user edits;"
            echo "                    the API key and any user-added keys are still preserved."
            exit 1
            ;;
    esac
done

# Create config directory if it doesn't exist
mkdir -p "$(dirname "$CONFIG_FILE")"

# Read existing values (if any) so re-installs preserve user edits.
# --force skips this, resetting the managed keys to defaults/template values.
# The API key is always reused regardless of --force (security rule: never
# replace an existing secret).
EXISTING_PREFIXES=""
EXISTING_DEBUG=""
if [ -f "$CONFIG_FILE" ] && [ "$FORCE" != "1" ]; then
    EXISTING_PREFIXES=$(grep '^CLAUDE_OFFICE_STRIP_PREFIXES=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'")
    EXISTING_DEBUG=$(grep '^CLAUDE_OFFICE_DEBUG=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2)
fi

# Precedence for STRIP_PREFIXES: --strip-prefixes flag > existing file > default.
if [ -n "$STRIP_PREFIXES" ]; then
    echo "Using custom strip prefixes: $STRIP_PREFIXES"
elif [ -n "$EXISTING_PREFIXES" ]; then
    STRIP_PREFIXES="$EXISTING_PREFIXES"
    echo "Preserving existing strip prefixes: $STRIP_PREFIXES"
else
    STRIP_PREFIXES="$DEFAULT_PREFIXES"
    echo "Using default strip prefixes: $STRIP_PREFIXES"
fi

# Precedence for DEBUG: existing file > 0 (default). --force resets to 0.
DEBUG_VALUE="${EXISTING_DEBUG:-0}"

# Generate or reuse API key for backend authentication.
# Security rule: NEVER replace an existing key, even under --force.
if [ -f "$CONFIG_FILE" ]; then
    EXISTING_KEY=$(grep '^CLAUDE_OFFICE_API_KEY=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2 | tr -d '"' | tr -d "'")
fi
if [ -n "$EXISTING_KEY" ]; then
    API_KEY="$EXISTING_KEY"
    echo "Reusing existing API key."
else
    API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    echo "Generated new API key."
fi

# Save configuration (read-modify-write per key).
# The heredoc rewrites only the three managed keys; any user-added keys from
# the existing file are appended afterwards, so re-installs no longer stomp
# user customizations. --force resets prefixes/debug but still preserves the
# API key and any user-added keys.
echo "Saving configuration to $CONFIG_FILE..."
if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.prev"
fi
cat > "$CONFIG_FILE" << EOF
# Claude Office Hooks Configuration
# Generated by install.sh

# Prefixes to strip from project names in the session browser
# Edit this and restart Claude Code to change
CLAUDE_OFFICE_STRIP_PREFIXES="$STRIP_PREFIXES"

# Set to 1 to enable debug logging
CLAUDE_OFFICE_DEBUG=$DEBUG_VALUE

# API key for backend authentication
CLAUDE_OFFICE_API_KEY="$API_KEY"
EOF
# Append user-added keys the installer doesn't manage (skip comments, blank
# lines, and the three managed keys).
if [ -f "$CONFIG_FILE.prev" ]; then
    grep -vE '^(#|CLAUDE_OFFICE_STRIP_PREFIXES=|CLAUDE_OFFICE_DEBUG=|CLAUDE_OFFICE_API_KEY=|$)' "$CONFIG_FILE.prev" >> "$CONFIG_FILE" 2>/dev/null || true
    rm -f "$CONFIG_FILE.prev"
fi

echo "Configuration saved."

# Install the python package as a tool
echo "Installing claude-office-hook tool..."
cd "$HOOKS_DIR"
uv tool install --force -p 3.14 .

# Use the command name directly - uv tool install adds it to PATH
# This is cross-platform compatible (works on macOS, Linux, and Windows)
HOOK_CMD="claude-office-hook"

# Verify the command is available
if ! command -v "$HOOK_CMD" &> /dev/null; then
    echo "Warning: '$HOOK_CMD' not found in PATH. You may need to add ~/.local/bin to your PATH."
    echo "Continuing with installation anyway..."
fi

echo "Configuring Claude settings..."

# Use the python script to manage settings safely
# Pass the hook command name (not full path) for cross-platform compatibility
uv run -p 3.14 "$HOOKS_DIR/manage_hooks.py" install --hook-cmd "$HOOK_CMD"

echo ""
echo "Done! Please restart Claude Code to apply changes."
echo ""
echo "Configuration file: $CONFIG_FILE"
echo "Edit this file to customize strip prefixes, then restart Claude Code."
